version: 2

sources:
  - name: spotify
    database: emilys-analytics
    schema: spotify_analytics
    tables:
      - name: raw_spotify_tracks
        description: "Raw Spotify tracks dataset uploaded manually from Kaggle."

